CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(45),
password VARCHAR(90),
logged_in BIT );
CREATE TABLE kingdoms (id INT AUTO_INCREMENT PRIMARY KEY, kingdomname VARCHAR(45));
