CREATE TABLE BUILDINGS (ID INT AUTO_INCREMENT PRIMARY KEY, TYPE VARCHAR(45), LEVEL SMALLINT (4),
                        HP SMALLINT (4), STARTED_AT SMALLINT (10), FINISHED_AT SMALLINT (10), FOREIGN KEY (kingdonm_id)
REFERENCES KINGDOMS (ID) );
